### ISSUE TITLE
Snapping issues/tolerence

### ISSUE THREAD

**Issue by USGSPMM3** [USGS-WiM/TravelTime#76]
I've had a handful of snaps where I click on the main river and it snaps to some other side channel. In the following screen shot on the Yellowstone River at Laurel, MT, I clicked on the "R" of Riverside Park.

![image](https://user-images.githubusercontent.com/16928289/73468075-78fcf380-4341-11ea-81c1-6747dd1e5fa8.png)

**Comment by tgross-usgs** [comment]
This has been happening since our December merge. I'm hopeful after all of Mitch's footer/chart changes that KJ and I will be able to eliminate this problem and at the same time get the map functioning in the report. In the meantime... drag the map before clicking on a spill location to avoid the tile shift.

**Comment by tim7en** [comment]
I am hoping to push updates on Monday. This is addressed and it is related to the vh set in the animation added for the footer.
