### ISSUE TITLE
relabel C(t) to Peak Concentration & Swap last two columns

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/TravelTime#79]
![image](https://user-images.githubusercontent.com/12058013/73860960-fde48300-4801-11ea-9236-458186e6c2a2.png)

**Comment by USGSPMM3** [comment]
Option A: Group the three travel times together and use a stacked heading over the three as they currently read. Make the upper heading read: "Travel time after spill"

Option B: Add "Travel time for" to each individual heading. Thus "Travel time for leading edge", "Travel time for peak concentration" etc.

**Comment by harper-wavra** [comment]
Seems like this table has been updated since this issue was created. It looks like the columns have the correct names and locations now. However it seems that "Time of" should be changed to "Travel time after spill." Is this correct?

![image](https://user-images.githubusercontent.com/59063181/89453269-9b266280-d724-11ea-92de-b04468c3e036.png)

**Comment by harper-wavra** [comment]
I am not sure if this issue is talking about the table in the footer, the report, or both (as they appear to be the same thing.) It seems like the table (footer and report) has been updated since this issue was created. It looks like the columns have the correct names and locations now. However it seems that "Time of" should be changed to "Travel time after spill." Is this correct? @USGSPMM3 
[Footer Table](https://user-images.githubusercontent.com/59063181/89453528-08d28e80-d725-11ea-8434-b0850ce803da.png)
[Header Table](https://user-images.githubusercontent.com/59063181/89453694-446d5880-d725-11ea-9164-3301f59be352.png)

**Comment by tgross-usgs** [comment]
I think they are probably taken care of now but you're right that the stacked header should probably read "Travel time after spill". Maybe check with @USGSPMM3 to see what he thinks.

**Comment by USGSPMM3** [comment]
![Table](https://user-images.githubusercontent.com/16928289/90033296-8c880000-dc7c-11ea-86e5-d64c828ea31d.PNG)
